[build-system]
requires = ["setuptools>=67", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "comfyai"
version = "0.1.0"
readme = "README.md"
dependencies = [
    "fastapi",
    "requests",
]

[project.optional-dependencies]
onnx = ["onnxruntime"]
dev = [
    "pytest",
    "fastapi[testclient]",
    "httpx",
]
torch = ["torch", "torchvision"]

[tool.setuptools]
packages = ["ComfyNodes", "transformer_worker"]
