jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install runtime
        run: pip install -r requirements.txt

      - name: Install dev
        run: pip install -r requirements-dev.txt

      - name: Run tests
        run: pytest -ra
